onPageShow: function() 
updateCoopLobby: function(coopGame) 
init: function(template) 
complete: base.onComplete(function(success, response) 
pluginState: null,patcherState: null,gameState: null,launcherState: null,inviteState: 
coopState: isHidden: true,checkboxes: 
installState: reservation: null,lastUIUpdate: null,states: 
resetPluginGameManager: function() 
addPluginPollCheck: function() 
getMatchmakeRules: function(callback) 
processMatchmakeRules: function(serverguideFilter) 
startCheckForGameUpToDate: function() 
updateGameStateUI: function() 
_updateCheckboxesInLocalStorage: function(name, value) 
hide: function() 
show: function() 
_checkOneTimeMessagesStatus: function() 
setTooltip: function(text) 
clearTooltip: function() 
updateGameStateUIFromState: function(state) 
_updateFromLocalStorage: function() 
getCurrentStateObject: function() 
saveLocalStorage: function(game) 
createGroupJoinToServer: function(server) 
clearLaunchState: function() 
saveLocalStorageAndUpdateUI: function(game) 
getState: function(callback) 
getPluginState: function(callback) 
getOriginState: function(callback) 
getGameState: function(callback) 
verifyPlugin: function() 
addToServerHistory: function(game, guid) 
inviteToCurrentServer: function(userId) 
launchAndJoin: function(server, friendPersonaId) 
leaveQueue: function() 
bindLaunchUpdates: function() 
gameStatePretty: function(gameState) 
maximiseCurrentGame: function() 
cancelGameLaunch: function(game) 
isCurrentPersona: function(personaId) 
handleErrors: function(game, personaId, errorType, errorCode) 
showLoaderError: function(errorMessage) 
handleWarnings: function(game, personaId, warningType, warningCode) 
showLoaderWarning: function(message) 
launchCampaign: function(game) 
loadMission: function(game, level, difficulty) 
resumeMission: function(game, level) 
countdownTimer: function(callback) 
joinReservation: function() 
coopPublicStart: function(coopGame) 