init: function(template) 
joinFriend: function(form) 
joinServerByUrl: function(url, friendPersonaId, callback) 
hasValidPlugin: function() 
checkJoinGameRequirements: function(callback, server, friendPersonaId) 
_joinServer: function(server, friendPersonaId) 
launch: function(server, friendPersonaId) 
hidePopup: function(conf) 
showPopup: function(name, state) 
showPasswordPromptPopup: function(server, callback) 
showJoinPartyInsteadPopup: function(data, callback) 
showNotValidPersonaPopup: function(server, friendPersonaId, callback) 
showPersonaPopup: function(server, friendPersonaId) 
complete: base.onComplete(function(success, response) 
showLoadingPopup: function(server) 
showGroupJoinPopup: function(server, friendPersonaId, callback) 
showPluginPopup: function(server, friendPersonaId, callback) 
showPatcherPopup: function(server, friendPersonaId, callback) 
showBFBC2ExePopup: function(server) 
showBC2PatchingNeededPopup: function() 
showInstallGameButton: function(server, friendPersonaId, callback) 
showPatchSuccessPopup: function(server) 
showLoginPopup: function(server, friendPersonaId) 
showPurchaseGameButton: function() 
showBuyPopup: function(server) 
showBuyView: function(element) 
error: function() 
_saveCurrentServerCookie: function(server, friendPersonaId) 
_saveCurrentServer: function(serverGame, serverGuid, friendPersonaId) 
_joinCurrentServer: function() 
_getCurrentServer: function() 
_deleteCurrentServer: function() 