onPageShow: function() 
updateFriendsPlayingOnServers: function() 
toggleRemoveFavorite: function() 
addFavorite: function(url, guid) 
updateInviteList: function(guid) 
removeOldStatesInInviteList: function() 
resetFilters: function(element) 
data: setFilterDescription: function() 
complete: base.onComplete(function(success, response) 
initSearchField: function() 
initPlugin: function() 
filterSurfaceTimeout: 0,initGuideFilters: function() 
greyOutGameSelectionMaps: function() 
disableNotOwnedExpansion: function() 
showQueryServerResult: function(game, server) 
inviteToServer: function(userId, guid) 
update_server_scoreboard: function() 
live_update_server_scoreboard: function() 
stop_update_server_scoreboard: function() 
registerForEvent: function(event, callback) 
_triggerEvent: function(event, data) 